on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: Read json data
    steps:
    - uses: actions/checkout@v2
    - name: Hello world action step
      id: hello
      uses: eddiejaoude/github-actions-reader-writer@master
      with:
        json-file-path: 'data.json'
        github-token: ${{ secrets.GITHUB_TOKEN }}
